# -*- coding: utf-8 -*-

CMD_NAME = {
    0x00: "status info",
    0x01: "error and warning info",
    0x02: "info 2",
    0x03: "firmware info",
    0x04: "serial number info",
    0x05: "hardware info",
    0x06: "communication error info",
    0x1b: "info request",
    0x1c: "reset",
    0x1d: "init boot",
    0x22: "init",
    0x23: "move",
    0x24: "discrete move",
    0x25: "rotate",
    0x26: "get movement data",
    0x27: "movement data",
    0x28: "set ramping",
    0x29: "get ramping",
    0x2B: "set discrete position",
    0x2C: "get discrete position",
    0x2f: "stop",
    0x40: "set port",
    0x41: "get port",
    0x42: "port data",
    0x43: "set port mode",
    0x44: "get port mode",
    0x45: "port mode data",
    0x46: "set port limit",
    0x47: "get port limit",
    0x48: "port limit data",
    0x49: "set port parameter",
    0x4A: "get port parameter",
    0x4B: "port parameter data",
    0x4C: "set port zero",
    0x53: "get aux data",
    0x55: "set aux data",
    0xdb: "get parameter",
    0xdc: "parameter data",
    0xde: "set parameter",
    0xef: "operate",
    0xfa: "set boot mode",
    0xfb: "get memory",
    0xfc: "memory data",
    0xfd: "erase memory",
    0xfe: "set memory",
    0xf8: "go boot",
    0xf9: "go main",
}
